USE [master]
GO

/****** Object:  Database [UrbanCompany]    Script Date: 15-02-2022 3.15.42 PM ******/
CREATE DATABASE [UrbanCompany]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UrbanCompany', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UrbanCompany.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UrbanCompany_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UrbanCompany_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UrbanCompany].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UrbanCompany] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UrbanCompany] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UrbanCompany] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UrbanCompany] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UrbanCompany] SET ARITHABORT OFF 
GO

ALTER DATABASE [UrbanCompany] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [UrbanCompany] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UrbanCompany] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UrbanCompany] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UrbanCompany] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UrbanCompany] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UrbanCompany] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UrbanCompany] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UrbanCompany] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UrbanCompany] SET  ENABLE_BROKER 
GO

ALTER DATABASE [UrbanCompany] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UrbanCompany] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UrbanCompany] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UrbanCompany] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UrbanCompany] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UrbanCompany] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [UrbanCompany] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UrbanCompany] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UrbanCompany] SET  MULTI_USER 
GO

ALTER DATABASE [UrbanCompany] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UrbanCompany] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UrbanCompany] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UrbanCompany] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UrbanCompany] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UrbanCompany] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UrbanCompany] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UrbanCompany] SET  READ_WRITE 
GO

